version: '3'
services:

    nginx:
        image: nginx:alpine
        container_name: barber_server
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=domain.tld
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=domain.tld
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./public_html:/app
        networks:
        - proxy
        restart: unless-stopped
